name: Docker image
on:
  push:
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          load: true
          push: false
          tags: openapitools/openapi-diff:${{ steps.vars.outputs.tag }}
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: openapitools/openapi-diff:${{ steps.vars.outputs.tag }}
          fail-build: false
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            openapitools/openapi-diff:${{ steps.vars.outputs.tag }}
            openapitools/openapi-diff:latest
