name: Manual Homebrew Update
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Version of the existing release to update Homebrew formula for (e.g., 2.1.0)'
        required: true

jobs:
  homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew Formula
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          token: ${{ secrets.HOMEBREW_PR_TOKEN }}
          formula: openapi-diff
          tag: ${{ github.event.inputs.releaseVersion }}